#### **1. Cargar datos**

In [1]:
import pandas as pd

df = pd.read_csv("C:/uk-train-rides-analysis/01_Data/railway.csv")

#### **2. Explorar**

In [2]:
# Vista de la tabla
df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,NaN,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,NaN,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,NaN,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

In [3]:
# Número de filas y columnas
df.shape

(31653, 18)

In [4]:
# Información de la tabla
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  str
 1   Date of Purchase     31653 non-null  str
 2   Time of Purchase     31653 non-null  str
 3   Purchase Type        31653 non-null  str
 4   Payment Method       31653 non-null  str
 5   Railcard             10735 non-null  str
 6   Ticket Class         31653 non-null  str
 7   Ticket Type          31653 non-null  str
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  str
 10  Arrival Destination  31653 non-null  str
 11  Date of Journey      31653 non-null  str
 12  Departure Time       31653 non-null  str
 13  Arrival Time         31653 non-null  str
 14  Actual Arrival Time  29773 non-null  str
 15  Journey Status       31653 non-null  str
 16  Reason for Delay     4172 non-null   str
 17  Refund Request       31653 non-null  str
dtypes: int64(1), str(17)
memory usage: 4.3 MB

In [5]:
# Valores nulos
df.isnull().sum()

Transaction ID             0
Date of Purchase           0
Time of Purchase           0
Purchase Type              0
Payment Method             0
Railcard               20918
Ticket Class               0
Ticket Type                0
Price                      0
Departure Station          0
Arrival Destination        0
Date of Journey            0
Departure Time             0
Arrival Time               0
Actual Arrival Time     1880
Journey Status             0
Reason for Delay       27481
Refund Request             0
dtype: int64

In [6]:
# Cantidad de valores únicos
for col in ['Purchase Type', 'Payment Method', 'Railcard', 'Ticket Class',
            'Ticket Type','Journey Status', 'Reason for Delay', 'Refund Request']:
    print(f"\n")
    print(df[col].value_counts(dropna=False))

Purchase Type
Online     18521
Station    13132
Name: count, dtype: int64


Payment Method
Credit Card    19136
Contactless    10834
Debit Card      1683
Name: count, dtype: int64


Railcard
NaN         20918
Adult        4846
Disabled     3089
Senior       2800
Name: count, dtype: int64


Ticket Class
Standard       28595
First Class     3058
Name: count, dtype: int64


Ticket Type
Advance     17561
Off-Peak     8752
Anytime      5340
Name: count, dtype: int64


Journey Status
On Time      27481
Delayed       2292
Cancelled     1880
Name: count, dtype: int64


Reason for Delay
NaN                   27481
Weather                 995
Technical Issue         707
Signal Failure          523
Signal failure          447
Staffing                410
Staff Shortage          399
Weather Conditions      377
Traffic                 314
Name: count, dtype: int64


Refund Request
No     30535
Yes     1118
Name: count, dtype: int64

In [7]:
# ¿Los valores nulos de "Actual Arrival Time" son por las cancelaciones?
pd.crosstab(
    df["Journey Status"],
    df["Actual Arrival Time"].isna()
)

Actual Arrival Time  False  True
Journey Status
Cancelled                0   1880
Delayed               2292      0
On Time              27481      0

In [8]:
# ¿Los valores nulos de "Reason for delay" son por que los viajes llegaron a tiempo?
pd.crosstab(
    df["Journey Status"],
    df["Reason for Delay"],
    dropna=False
)

Reason for Delay,Signal Failure,Signal failure,Staff Shortage,Staffing,Technical Issue,Traffic,Weather,Weather Conditions,NaN
Journey Status,,,,,,,,,
Cancelled,281,238,216,238,235,227,237,208,0
Delayed,242,209,183,172,472,87,758,169,0
On Time,0,0,0,0,0,0,0,0,27481

In [9]:
# ¿Existen devoluciones en los viajes a tiempo?
pd.crosstab(
    df["Journey Status"],
    df["Refund Request"],
    dropna=False
)

Refund Request     No  Yes
Journey Status
Cancelled        1308  572
Delayed          1746  546
On Time         27481    0

#### **3. Limpiar**

##### **3.1 Reemplazar los nulos en "Railcard"**

In [10]:
df['Railcard'] = df['Railcard'].fillna('No Railcard')

df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,Arrival Destination,Date of Journey,Departure Time,Arrival Time,Actual Arrival Time,Journey Status,Reason for Delay,Refund Request
0,da8a6ba8-b3dc-4677-b176,2023-12-08,12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,Liverpool Lime Street,2024-01-01,11:00:00,13:30:00,13:30:00,On Time,NaN,No
1,b0cdd1b0-f214-4197-be53,2023-12-16,11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,York,2024-01-01,09:45:00,11:35:00,11:40:00,Delayed,Signal Failure,No
2,f3ba7a96-f713-40d9-9629,2023-12-19,19:51:27,Online,Credit Card,No Railcard,Standard,Advance,3,Liverpool Lime Street,Manchester Piccadilly,2024-01-02,18:15:00,18:45:00,18:45:00,On Time,NaN,No
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,23:00:36,Station,Credit Card,No Railcard,Standard,Advance,13,London Paddington,Reading,2024-01-01,21:30:00,22:30:00,22:30:00,On Time,NaN,No
4,2be00b45-0762-485e-a7a3,2023-12-27,18:22:56,Online,Contactless,No Railcard,Standard,Advance,76,Liverpool Lime Street,London Euston,2024-01-01,16:45:00,19:00:00,19:00:00,On Time,NaN,No

##### **3.2 Conversión de fechas y horas**

In [11]:
# Fecha
df['Date of Purchase'] = pd.to_datetime(df['Date of Purchase'], format='%Y-%m-%d')
df['Date of Journey'] = pd.to_datetime(df['Date of Journey'], format='%Y-%m-%d')

# Hora
columnas_hora = ['Time of Purchase', 'Departure Time', 'Arrival Time', 'Actual Arrival Time']

for col in columnas_hora:
    df[col] = pd.to_datetime(
        df[col],
        format='%H:%M:%S',
        errors='coerce'
    )

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       31653 non-null  str
 1   Date of Purchase     31653 non-null  datetime64[us]
 2   Time of Purchase     31653 non-null  datetime64[us]
 3   Purchase Type        31653 non-null  str
 4   Payment Method       31653 non-null  str
 5   Railcard             31653 non-null  str
 6   Ticket Class         31653 non-null  str
 7   Ticket Type          31653 non-null  str
 8   Price                31653 non-null  int64
 9   Departure Station    31653 non-null  str
 10  Arrival Destination  31653 non-null  str
 11  Date of Journey      31653 non-null  datetime64[us]
 12  Departure Time       31653 non-null  datetime64[us]
 13  Arrival Time         31653 non-null  datetime64[us]
 14  Actual Arrival Time  29773 non-null  datetime64[us]
 15  Journey Status       31653 non-null  str
 16  Reason for Delay     4172 non-null   str
 17  Refund Request       31653 non-null  str
dtypes: datetime64[us](6), int64(1), str(11)
memory usage: 4.3 MB

##### **3.3 Agrupar variables equivalentes**

In [12]:
df['Reason for Delay'] = df['Reason for Delay'].replace(
    ['Signal failure', 'Staff Shortage', 'Weather Conditions'], 
    ['Signal Failure', 'Staffing', 'Weather']
)

df['Reason for Delay'].value_counts(dropna=False)

Reason for Delay
NaN                27481
Weather             1372
Signal Failure       970
Staffing             809
Technical Issue      707
Traffic              314
Name: count, dtype: int64

#### **4. Nuevas variables**

In [13]:
# 1.Ruta
df['Route'] = df['Departure Station'].str.strip() + ' → ' + df['Arrival Destination'].str.strip()

# 2.Hora de salida
df['Departure Hour'] = df['Departure Time'].dt.hour

# 3.Franja horaria
df['Time Slot'] = pd.cut(
    df['Departure Hour'],
    bins=[0, 6, 12, 14, 18, 24],
    labels=[
        'Early Morning',
        'Morning',
        'Midday',
        'Afternoon',
        'Night'
    ],
    right=False
)

# 4. Día de la semana
df['Day of Week'] = df['Date of Journey'].dt.day_name()

# 5. Duración programada
# 5.1 Crear fecha y hora programadas de salida y llegada
fecha_viaje = df['Date of Journey'].dt.strftime('%Y-%m-%d')

df['Scheduled Departure'] = pd.to_datetime(fecha_viaje + ' ' + df['Departure Time'].dt.strftime('%H:%M:%S'), errors='coerce')

df['Scheduled Arrival'] = pd.to_datetime(fecha_viaje + ' ' + df['Arrival Time'].dt.strftime('%H:%M:%S'), errors='coerce')

# 5.2 Si la llegada programada ocurre después de medianoche
mask = df['Scheduled Arrival'] < df['Scheduled Departure']

df.loc[mask, 'Scheduled Arrival'] += pd.Timedelta(days=1)

# 5.3 Crear fecha y hora de llegada real
df['Actual Arrival'] = pd.to_datetime(
    fecha_viaje + ' ' +
    df['Actual Arrival Time'].dt.strftime('%H:%M:%S'),
    errors='coerce'
)

# 5.4 Ajustar llegadas reales que ocurren después de medianoche
mask_actual = (df['Actual Arrival'].notna() & (df['Actual Arrival'] < df['Scheduled Departure']))

df.loc[mask_actual, 'Actual Arrival'] += pd.Timedelta(days=1)

# 5.5 Duración programada del viaje, en minutos
df['Scheduled Journey Minutes'] = ((df['Scheduled Arrival'] - df['Scheduled Departure']).dt.total_seconds() / 60)

# 6. Minutos de retraso
df['Delay Minutes'] = ((df['Actual Arrival'] - df['Scheduled Arrival']).dt.total_seconds() / 60)

# 7. Anticipación de compra
df['Booking Lead Time'] = (df['Date of Journey'] - df['Date of Purchase']).dt.days

df.head()

,Transaction ID,Date of Purchase,Time of Purchase,Purchase Type,Payment Method,Railcard,Ticket Class,Ticket Type,Price,Departure Station,...,Route,Departure Hour,Time Slot,Day of Week,Scheduled Departure,Scheduled Arrival,Actual Arrival,Scheduled Journey Minutes,Delay Minutes,Booking Lead Time
0,da8a6ba8-b3dc-4677-b176,2023-12-08,1900-01-01 12:41:11,Online,Contactless,Adult,Standard,Advance,43,London Paddington,...,London Paddington → Liverpool Lime Street,11,Morning,Monday,2024-01-01 11:00:00,2024-01-01 13:30:00,2024-01-01 13:30:00,150.0,0.0,24
1,b0cdd1b0-f214-4197-be53,2023-12-16,1900-01-01 11:23:01,Station,Credit Card,Adult,Standard,Advance,23,London Kings Cross,...,London Kings Cross → York,9,Morning,Monday,2024-01-01 09:45:00,2024-01-01 11:35:00,2024-01-01 11:40:00,110.0,5.0,16
2,f3ba7a96-f713-40d9-9629,2023-12-19,1900-01-01 19:51:27,Online,Credit Card,No Railcard,Standard,Advance,3,Liverpool Lime Street,...,Liverpool Lime Street → Manchester Piccadilly,18,Night,Tuesday,2024-01-02 18:15:00,2024-01-02 18:45:00,2024-01-02 18:45:00,30.0,0.0,14
3,b2471f11-4fe7-4c87-8ab4,2023-12-20,1900-01-01 23:00:36,Station,Credit Card,No Railcard,Standard,Advance,13,London Paddington,...,London Paddington → Reading,21,Night,Monday,2024-01-01 21:30:00,2024-01-01 22:30:00,2024-01-01 22:30:00,60.0,0.0,12
4,2be00b45-0762-485e-a7a3,2023-12-27,1900-01-01 18:22:56,Online,Contactless,No Railcard,Standard,Advance,76,Liverpool Lime Street,...,Liverpool Lime Street → London Euston,16,Afternoon,Monday,2024-01-01 16:45:00,2024-01-01 19:00:00,2024-01-01 19:00:00,135.0,0.0,5

#### **5. Exportar**

In [14]:
df.to_csv('C:/uk-train-rides-analysis/01_Data/railway_clean.csv', index=False)